"
Colored Semantic UI style
"
Trait {
	#name : #SUIColored,
	#category : #'Seaside-SemanticUI-Core-Traits'
}

{ #category : #coloring }
SUIColored >> beBlue [

	self class: 'blue'
]

{ #category : #coloring }
SUIColored >> beBrown [

	self class: 'brown'
]

{ #category : #coloring }
SUIColored >> beGreen [

	self class: 'green'
]

{ #category : #coloring }
SUIColored >> beGrey [

	self class: 'grey'
]

{ #category : #coloring }
SUIColored >> beOlive [

	self class: 'olive'
]

{ #category : #coloring }
SUIColored >> beOrange [

	self class: 'orange'
]

{ #category : #coloring }
SUIColored >> bePink [

	self class: 'pink'
]

{ #category : #coloring }
SUIColored >> bePurple [

	self class: 'purple'
]

{ #category : #coloring }
SUIColored >> beRed [

	self class: 'red'
]

{ #category : #coloring }
SUIColored >> beTeal [

	self class: 'teal'
]

{ #category : #coloring }
SUIColored >> beViolet [

	self class: 'violet'
]

{ #category : #coloring }
SUIColored >> beYellow [

	self class: 'yellow'
]
