"
Provides size
"
Trait {
	#name : #SUISized,
	#category : #'Seaside-SemanticUI-Core-Traits'
}

{ #category : #sizing }
SUISized >> beBig [

	self class: 'big'
]

{ #category : #sizing }
SUISized >> beHuge [

	self class: 'huge'
]

{ #category : #sizing }
SUISized >> beLarge [

	self class: 'large'
]

{ #category : #sizing }
SUISized >> beMassive [

	self class: 'massive'
]

{ #category : #sizing }
SUISized >> beMedium [

	self class: 'medium'
]

{ #category : #sizing }
SUISized >> beMini [

	self class: 'mini'
]

{ #category : #sizing }
SUISized >> beSmall [

	self class: 'small'
]

{ #category : #sizing }
SUISized >> beTiny [

	self class: 'tiny'
]
