Extension { #name : #WAButtonTag }

{ #category : #'*Seaside-SemanticUI-Core' }
WAButtonTag >> beAnimated [

	self class: 'animated'
]

{ #category : #'*Seaside-SemanticUI-Core' }
WAButtonTag >> beBasic [

	self class: 'basic'
]

{ #category : #'*Seaside-SemanticUI-Core' }
WAButtonTag >> beIcon [

	self class: 'icon'
]

{ #category : #'*Seaside-SemanticUI-Core' }
WAButtonTag >> beLabeled [

	self class: 'labeled'
]

{ #category : #'*Seaside-SemanticUI-Core' }
WAButtonTag >> beLabeledIcon [

	self class: 'labeled icon'
]

{ #category : #'*Seaside-SemanticUI-Core' }
WAButtonTag >> beNegative [

	self class: 'negative'
]

{ #category : #'*Seaside-SemanticUI-Core' }
WAButtonTag >> bePositive [

	self class: 'positive'
]

{ #category : #'*Seaside-SemanticUI-Core' }
WAButtonTag >> bePrimary [

	self class: 'primary'
]

{ #category : #'*Seaside-SemanticUI-Core' }
WAButtonTag >> beSecondary [

	self class: 'secondary'
]

{ #category : #'*Seaside-SemanticUI-Core' }
WAButtonTag >> black [

	self class: 'black'
]

{ #category : #'*Seaside-SemanticUI-Core' }
WAButtonTag >> blue [

	self class: 'blue'
]

{ #category : #'*Seaside-SemanticUI-Core' }
WAButtonTag >> brown [

	self class: 'brown'
]

{ #category : #'*Seaside-SemanticUI-Core' }
WAButtonTag >> green [

	self class: 'green'
]

{ #category : #'*Seaside-SemanticUI-Core' }
WAButtonTag >> grey [

	self class: 'grey'
]

{ #category : #'*Seaside-SemanticUI-Core' }
WAButtonTag >> inverted [

	self class: 'inverted'
]

{ #category : #'*Seaside-SemanticUI-Core' }
WAButtonTag >> olive [

	self class: 'olive'
]

{ #category : #'*Seaside-SemanticUI-Core' }
WAButtonTag >> orange [

	self class: 'orange'
]

{ #category : #'*Seaside-SemanticUI-Core' }
WAButtonTag >> pink [

	self class: 'pink'
]

{ #category : #'*Seaside-SemanticUI-Core' }
WAButtonTag >> purple [

	self class: 'purple'
]

{ #category : #'*Seaside-SemanticUI-Core' }
WAButtonTag >> red [

	self class: 'red'
]

{ #category : #'*Seaside-SemanticUI-Core' }
WAButtonTag >> teal [

	self class: 'teal'
]

{ #category : #'*Seaside-SemanticUI-Core' }
WAButtonTag >> violet [

	self class: 'violet'
]

{ #category : #'*Seaside-SemanticUI-Core' }
WAButtonTag >> yellow [

	self class: 'yellow'
]
