Extension { #name : #WAButtonTag }

{ #category : #'*Seaside-SemanticUI-Core' }
WAButtonTag >> beAnimated [

	self class: 'animated'
]

{ #category : #'*Seaside-SemanticUI-Core' }
WAButtonTag >> beLabeled [

	self class: 'labeled'
]

{ #category : #'*Seaside-SemanticUI-Core' }
WAButtonTag >> bePrimary [

	self class: 'primary'
]

{ #category : #'*Seaside-SemanticUI-Core' }
WAButtonTag >> beSecondary [

	self class: 'secondary'
]
