Extension { #name : #WAButtonTag }

{ #category : #'*Seaside-SemanticUI-Core' }
WAButtonTag >> beActive [

	self class: 'active'
]

{ #category : #'*Seaside-SemanticUI-Core' }
WAButtonTag >> beAnimated [

	self class: 'animated'
]

{ #category : #'*Seaside-SemanticUI-Core' }
WAButtonTag >> beBasic [

	self class: 'basic'
]

{ #category : #'*Seaside-SemanticUI-Core' }
WAButtonTag >> beDisabled [

	self class: 'disabled'
]

{ #category : #'*Seaside-SemanticUI-Core' }
WAButtonTag >> beFacebook [

	self class: 'facebook'
]

{ #category : #'*Seaside-SemanticUI-Core' }
WAButtonTag >> beGooglePlus [

	self class: 'google plus'
]

{ #category : #'*Seaside-SemanticUI-Core' }
WAButtonTag >> beIcon [

	self class: 'icon'
]

{ #category : #'*Seaside-SemanticUI-Core' }
WAButtonTag >> beInstagram [

	self class: 'instagram'
]

{ #category : #'*Seaside-SemanticUI-Core' }
WAButtonTag >> beLabeled [

	self class: 'labeled'
]

{ #category : #'*Seaside-SemanticUI-Core' }
WAButtonTag >> beLabeledIcon [

	self class: 'labeled icon'
]

{ #category : #'*Seaside-SemanticUI-Core' }
WAButtonTag >> beLinkedIn [

	self class: 'linkedin'
]

{ #category : #'*Seaside-SemanticUI-Core' }
WAButtonTag >> beLoading [

	self class: 'loading'
]

{ #category : #'*Seaside-SemanticUI-Core' }
WAButtonTag >> beNegative [

	self class: 'negative'
]

{ #category : #'*Seaside-SemanticUI-Core' }
WAButtonTag >> bePositive [

	self class: 'positive'
]

{ #category : #'*Seaside-SemanticUI-Core' }
WAButtonTag >> bePrimary [

	self class: 'primary'
]

{ #category : #'*Seaside-SemanticUI-Core' }
WAButtonTag >> beSecondary [

	self class: 'secondary'
]

{ #category : #'*Seaside-SemanticUI-Core' }
WAButtonTag >> beTwitter [

	self class: 'twitter'
]

{ #category : #'*Seaside-SemanticUI-Core' }
WAButtonTag >> beVK [

	self class: 'vk'
]

{ #category : #'*Seaside-SemanticUI-Core' }
WAButtonTag >> beYoutube [

	self class: 'youtube'
]

{ #category : #'*Seaside-SemanticUI-Core' }
WAButtonTag >> big [

	self class: 'big'
]

{ #category : #'*Seaside-SemanticUI-Core' }
WAButtonTag >> black [

	self class: 'black'
]

{ #category : #'*Seaside-SemanticUI-Core' }
WAButtonTag >> blue [

	self class: 'blue'
]

{ #category : #'*Seaside-SemanticUI-Core' }
WAButtonTag >> brown [

	self class: 'brown'
]

{ #category : #'*Seaside-SemanticUI-Core' }
WAButtonTag >> green [

	self class: 'green'
]

{ #category : #'*Seaside-SemanticUI-Core' }
WAButtonTag >> grey [

	self class: 'grey'
]

{ #category : #'*Seaside-SemanticUI-Core' }
WAButtonTag >> huge [

	self class: 'huge'
]

{ #category : #'*Seaside-SemanticUI-Core' }
WAButtonTag >> inverted [

	self class: 'inverted'
]

{ #category : #'*Seaside-SemanticUI-Core' }
WAButtonTag >> large [

	self class: 'large'
]

{ #category : #'*Seaside-SemanticUI-Core' }
WAButtonTag >> massive [

	self class: 'massive'
]

{ #category : #'*Seaside-SemanticUI-Core' }
WAButtonTag >> medium [

	self class: 'medium'
]

{ #category : #'*Seaside-SemanticUI-Core' }
WAButtonTag >> mini [

	self class: 'mini'
]

{ #category : #'*Seaside-SemanticUI-Core' }
WAButtonTag >> olive [

	self class: 'olive'
]

{ #category : #'*Seaside-SemanticUI-Core' }
WAButtonTag >> orange [

	self class: 'orange'
]

{ #category : #'*Seaside-SemanticUI-Core' }
WAButtonTag >> pink [

	self class: 'pink'
]

{ #category : #'*Seaside-SemanticUI-Core' }
WAButtonTag >> purple [

	self class: 'purple'
]

{ #category : #'*Seaside-SemanticUI-Core' }
WAButtonTag >> red [

	self class: 'red'
]

{ #category : #'*Seaside-SemanticUI-Core' }
WAButtonTag >> small [

	self class: 'small'
]

{ #category : #'*Seaside-SemanticUI-Core' }
WAButtonTag >> teal [

	self class: 'teal'
]

{ #category : #'*Seaside-SemanticUI-Core' }
WAButtonTag >> tiny [

	self class: 'tiny'
]

{ #category : #'*Seaside-SemanticUI-Core' }
WAButtonTag >> violet [

	self class: 'violet'
]

{ #category : #'*Seaside-SemanticUI-Core' }
WAButtonTag >> yellow [

	self class: 'yellow'
]
